import libDatToXyz;
import std.getopt;
void main(string[] args){
    string inFname, outFname;
    float middleFrequency, octavesPerAngstrom, middleDuration, durationFoldPerAngstrom, coordCutoff;
    auto helpInfo = getopt(args,
            "in", "The name of the csv file generated by jsonToDat", &inFname,
            "xyz", "The name of the xyz-format file to write.", &outFname,
            "middle-frequency", "The frequency of an atom at zero angstroms", &middleFrequency,
            "octaves-per-angstrom", "How many octaves are traversed per angstrom?", &octavesPerAngstrom,
            "middle-length", "The length of a note at zero angstroms", &middleDuration,
            "duration-fold-per-angstrom", "How many times longer does a note get every angstrom?", &durationFoldPerAngstrom,
            "coord-cutoff", "For dynamics, what are the maximal and minimal coordinates?", &coordCutoff);
    if(helpInfo.helpWanted){
        defaultGetoptPrinter("Convert a csv file with note parameters into an xyz file that can be loaded with vmd.",
                helpInfo.options);
        return;
    }
    runToXyz(inFname, outFname, middleFrequency, octavesPerAngstrom, middleDuration, durationFoldPerAngstrom, coordCutoff);
}
